[package]
name = "audio-af"
version = "0.1.0"
authors = ["SEGFAULT", "Spacekookie"]
edition = "2018"

[dependencies]
num = "0.3"
sample = "0.10"
portaudio = "0.7"
audio-af-macros = {path = "../audio-af-macros"}